services:
  mulia-wisata:
    build: .
    container_name: mulia-wisata
    restart: unless-stopped
    ports:
      - "3003:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    volumes:
      - mulia_wisata_uploads:/app/uploads
      - mulia_wisata_data:/app/data

volumes:
  mulia_wisata_uploads:
  mulia_wisata_data:
